import fs from 'node:fs';
import path from 'node:path';

export type ManifestCategory =
  | 'concepts'
  | 'system-design-case-studies'
  | 'oo-case-studies'
  | 'flashcards'
  | 'design-patterns';

export interface ManifestEntry {
  id: string;
  title: string;
  path: string;
  category: ManifestCategory;
  source?: 'primer' | 'supplementary';
}

export function buildManifest(
  concepts: { slug: string; title: string }[],
  systemDesignCaseStudies: { slug: string; title: string }[],
  oodCaseStudies: { slug: string; title: string }[],
  flashcardDecks: { deckId: string; title: string }[],
): ManifestEntry[] {
  const entries: ManifestEntry[] = [];
  for (const c of concepts) {
    entries.push({ id: `concepts/${c.slug}`, title: c.title, path: `/docs/concepts/${c.slug}`, category: 'concepts' });
  }
  for (const c of systemDesignCaseStudies) {
    entries.push({
      id: `case-studies/system-design/${c.slug}`,
      title: c.title,
      path: `/docs/case-studies/system-design/${c.slug}`,
      category: 'system-design-case-studies',
    });
  }
  for (const c of oodCaseStudies) {
    entries.push({
      id: `case-studies/object-oriented-design/${c.slug}`,
      title: c.title,
      path: `/docs/case-studies/object-oriented-design/${c.slug}`,
      category: 'oo-case-studies',
    });
  }
  for (const d of flashcardDecks) {
    entries.push({ id: `flashcards/${d.deckId}`, title: d.title, path: `/flashcards/${d.deckId}`, category: 'flashcards' });
  }
  return entries;
}

export function writeManifestFile(entries: ManifestEntry[], outFile: string): void {
  const body = `// Generated by scripts/ingest/run.ts — do not edit by hand.
export type ManifestCategory =
  | 'concepts'
  | 'system-design-case-studies'
  | 'oo-case-studies'
  | 'flashcards'
  | 'design-patterns';

export interface ManifestEntry {
  id: string;
  title: string;
  path: string;
  category: ManifestCategory;
  source?: 'primer' | 'supplementary';
}

export const courseManifest: ManifestEntry[] = ${JSON.stringify(entries, null, 2)};
`;
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body);
}
