// Generated by scripts/ingest/run.ts — do not edit by hand.
export type ManifestCategory = 'concepts' | 'system-design-case-studies' | 'oo-case-studies' | 'flashcards';

export interface ManifestEntry {
  id: string;
  title: string;
  path: string;
  category: ManifestCategory;
}

export const courseManifest: ManifestEntry[] = [
  {
    "id": "concepts/study-guide",
    "title": "Study Guide",
    "path": "/docs/concepts/study-guide",
    "category": "concepts"
  },
  {
    "id": "concepts/interview-approach",
    "title": "How to Approach a System Design Interview Question",
    "path": "/docs/concepts/interview-approach",
    "category": "concepts"
  },
  {
    "id": "concepts/start-here",
    "title": "System Design Topics: Start Here",
    "path": "/docs/concepts/start-here",
    "category": "concepts"
  },
  {
    "id": "concepts/performance-vs-scalability",
    "title": "Performance vs Scalability",
    "path": "/docs/concepts/performance-vs-scalability",
    "category": "concepts"
  },
  {
    "id": "concepts/latency-vs-throughput",
    "title": "Latency vs Throughput",
    "path": "/docs/concepts/latency-vs-throughput",
    "category": "concepts"
  },
  {
    "id": "concepts/availability-vs-consistency",
    "title": "Availability vs Consistency",
    "path": "/docs/concepts/availability-vs-consistency",
    "category": "concepts"
  },
  {
    "id": "concepts/consistency-patterns",
    "title": "Consistency Patterns",
    "path": "/docs/concepts/consistency-patterns",
    "category": "concepts"
  },
  {
    "id": "concepts/availability-patterns",
    "title": "Availability Patterns",
    "path": "/docs/concepts/availability-patterns",
    "category": "concepts"
  },
  {
    "id": "concepts/dns",
    "title": "Domain Name System",
    "path": "/docs/concepts/dns",
    "category": "concepts"
  },
  {
    "id": "concepts/cdn",
    "title": "Content Delivery Network",
    "path": "/docs/concepts/cdn",
    "category": "concepts"
  },
  {
    "id": "concepts/load-balancer",
    "title": "Load Balancer",
    "path": "/docs/concepts/load-balancer",
    "category": "concepts"
  },
  {
    "id": "concepts/reverse-proxy",
    "title": "Reverse Proxy",
    "path": "/docs/concepts/reverse-proxy",
    "category": "concepts"
  },
  {
    "id": "concepts/application-layer",
    "title": "Application Layer",
    "path": "/docs/concepts/application-layer",
    "category": "concepts"
  },
  {
    "id": "concepts/database",
    "title": "Database",
    "path": "/docs/concepts/database",
    "category": "concepts"
  },
  {
    "id": "concepts/cache",
    "title": "Cache",
    "path": "/docs/concepts/cache",
    "category": "concepts"
  },
  {
    "id": "concepts/asynchronism",
    "title": "Asynchronism",
    "path": "/docs/concepts/asynchronism",
    "category": "concepts"
  },
  {
    "id": "concepts/communication",
    "title": "Communication",
    "path": "/docs/concepts/communication",
    "category": "concepts"
  },
  {
    "id": "concepts/security",
    "title": "Security",
    "path": "/docs/concepts/security",
    "category": "concepts"
  },
  {
    "id": "concepts/appendix",
    "title": "Appendix",
    "path": "/docs/concepts/appendix",
    "category": "concepts"
  },
  {
    "id": "case-studies/system-design/pastebin",
    "title": "Design Pastebin.com (or Bit.ly)",
    "path": "/docs/case-studies/system-design/pastebin",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/system-design/twitter",
    "title": "Design the Twitter Timeline and Search",
    "path": "/docs/case-studies/system-design/twitter",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/system-design/web-crawler",
    "title": "Design a Web Crawler",
    "path": "/docs/case-studies/system-design/web-crawler",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/system-design/mint",
    "title": "Design Mint.com",
    "path": "/docs/case-studies/system-design/mint",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/system-design/social-graph",
    "title": "Design the Data Structures for a Social Network",
    "path": "/docs/case-studies/system-design/social-graph",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/system-design/query-cache",
    "title": "Design a Key-Value Cache for Web Server Query Results",
    "path": "/docs/case-studies/system-design/query-cache",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/system-design/sales-rank",
    "title": "Design Amazon's Sales Rank by Category Feature",
    "path": "/docs/case-studies/system-design/sales-rank",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/system-design/scaling-aws",
    "title": "Design a System That Scales to Millions of Users on AWS",
    "path": "/docs/case-studies/system-design/scaling-aws",
    "category": "system-design-case-studies"
  },
  {
    "id": "case-studies/object-oriented-design/deck-of-cards",
    "title": "Design a Deck of Cards",
    "path": "/docs/case-studies/object-oriented-design/deck-of-cards",
    "category": "oo-case-studies"
  },
  {
    "id": "case-studies/object-oriented-design/call-center",
    "title": "Design a Call Center",
    "path": "/docs/case-studies/object-oriented-design/call-center",
    "category": "oo-case-studies"
  },
  {
    "id": "case-studies/object-oriented-design/lru-cache",
    "title": "Design an LRU Cache",
    "path": "/docs/case-studies/object-oriented-design/lru-cache",
    "category": "oo-case-studies"
  },
  {
    "id": "case-studies/object-oriented-design/hash-table",
    "title": "Design a Hashmap",
    "path": "/docs/case-studies/object-oriented-design/hash-table",
    "category": "oo-case-studies"
  },
  {
    "id": "case-studies/object-oriented-design/parking-lot",
    "title": "Design a Parking Lot",
    "path": "/docs/case-studies/object-oriented-design/parking-lot",
    "category": "oo-case-studies"
  },
  {
    "id": "case-studies/object-oriented-design/online-chat",
    "title": "Design Online Chat",
    "path": "/docs/case-studies/object-oriented-design/online-chat",
    "category": "oo-case-studies"
  },
  {
    "id": "flashcards/system-design",
    "title": "System Design",
    "path": "/flashcards/system-design",
    "category": "flashcards"
  },
  {
    "id": "flashcards/system-design-exercises",
    "title": "System Design Exercises",
    "path": "/flashcards/system-design-exercises",
    "category": "flashcards"
  },
  {
    "id": "flashcards/oo-design",
    "title": "OO Design",
    "path": "/flashcards/oo-design",
    "category": "flashcards"
  }
];
