// Generated by scripts/ingest/run.ts — do not edit by hand.
export type ManifestCategory =
  | 'concepts'
  | 'system-design-case-studies'
  | 'oo-case-studies'
  | 'flashcards'
  | 'design-patterns';

export interface ManifestEntry {
  id: string;
  title: string;
  path: string;
  category: ManifestCategory;
  source?: 'primer' | 'supplementary';
}

export const courseManifest: ManifestEntry[] = [
  {
    "id": "concepts/study-guide",
    "title": "Study Guide",
    "path": "/docs/concepts/study-guide",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/interview-approach",
    "title": "How to Approach a System Design Interview Question",
    "path": "/docs/concepts/interview-approach",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/start-here",
    "title": "System Design Topics: Start Here",
    "path": "/docs/concepts/start-here",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/performance-vs-scalability",
    "title": "Performance vs Scalability",
    "path": "/docs/concepts/performance-vs-scalability",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/latency-vs-throughput",
    "title": "Latency vs Throughput",
    "path": "/docs/concepts/latency-vs-throughput",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/availability-vs-consistency",
    "title": "Availability vs Consistency",
    "path": "/docs/concepts/availability-vs-consistency",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/consistency-patterns",
    "title": "Consistency Patterns",
    "path": "/docs/concepts/consistency-patterns",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/availability-patterns",
    "title": "Availability Patterns",
    "path": "/docs/concepts/availability-patterns",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/dns",
    "title": "Domain Name System",
    "path": "/docs/concepts/dns",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/cdn",
    "title": "Content Delivery Network",
    "path": "/docs/concepts/cdn",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/load-balancer",
    "title": "Load Balancer",
    "path": "/docs/concepts/load-balancer",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/reverse-proxy",
    "title": "Reverse Proxy",
    "path": "/docs/concepts/reverse-proxy",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/application-layer",
    "title": "Application Layer",
    "path": "/docs/concepts/application-layer",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/database",
    "title": "Database",
    "path": "/docs/concepts/database",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/cache",
    "title": "Cache",
    "path": "/docs/concepts/cache",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/asynchronism",
    "title": "Asynchronism",
    "path": "/docs/concepts/asynchronism",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/communication",
    "title": "Communication",
    "path": "/docs/concepts/communication",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/security",
    "title": "Security",
    "path": "/docs/concepts/security",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "concepts/appendix",
    "title": "Appendix",
    "path": "/docs/concepts/appendix",
    "category": "concepts",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/pastebin",
    "title": "Design Pastebin.com (or Bit.ly)",
    "path": "/docs/case-studies/system-design/pastebin",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/twitter",
    "title": "Design the Twitter Timeline and Search",
    "path": "/docs/case-studies/system-design/twitter",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/web-crawler",
    "title": "Design a Web Crawler",
    "path": "/docs/case-studies/system-design/web-crawler",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/mint",
    "title": "Design Mint.com",
    "path": "/docs/case-studies/system-design/mint",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/social-graph",
    "title": "Design the Data Structures for a Social Network",
    "path": "/docs/case-studies/system-design/social-graph",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/query-cache",
    "title": "Design a Key-Value Cache for Web Server Query Results",
    "path": "/docs/case-studies/system-design/query-cache",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/sales-rank",
    "title": "Design Amazon's Sales Rank by Category Feature",
    "path": "/docs/case-studies/system-design/sales-rank",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/system-design/scaling-aws",
    "title": "Design a System That Scales to Millions of Users on AWS",
    "path": "/docs/case-studies/system-design/scaling-aws",
    "category": "system-design-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/object-oriented-design/deck-of-cards",
    "title": "Design a Deck of Cards",
    "path": "/docs/case-studies/object-oriented-design/deck-of-cards",
    "category": "oo-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/object-oriented-design/call-center",
    "title": "Design a Call Center",
    "path": "/docs/case-studies/object-oriented-design/call-center",
    "category": "oo-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/object-oriented-design/lru-cache",
    "title": "Design an LRU Cache",
    "path": "/docs/case-studies/object-oriented-design/lru-cache",
    "category": "oo-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/object-oriented-design/hash-table",
    "title": "Design a Hashmap",
    "path": "/docs/case-studies/object-oriented-design/hash-table",
    "category": "oo-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/object-oriented-design/parking-lot",
    "title": "Design a Parking Lot",
    "path": "/docs/case-studies/object-oriented-design/parking-lot",
    "category": "oo-case-studies",
    "source": "primer"
  },
  {
    "id": "case-studies/object-oriented-design/online-chat",
    "title": "Design Online Chat",
    "path": "/docs/case-studies/object-oriented-design/online-chat",
    "category": "oo-case-studies",
    "source": "primer"
  },
  {
    "id": "flashcards/system-design",
    "title": "System Design",
    "path": "/flashcards/system-design",
    "category": "flashcards",
    "source": "primer"
  },
  {
    "id": "flashcards/system-design-exercises",
    "title": "System Design Exercises",
    "path": "/flashcards/system-design-exercises",
    "category": "flashcards",
    "source": "primer"
  },
  {
    "id": "flashcards/oo-design",
    "title": "OO Design",
    "path": "/flashcards/oo-design",
    "category": "flashcards",
    "source": "primer"
  },
  {
    "id": "patterns/ai-agent-orchestration/concurrent-orchestration",
    "title": "Concurrent Orchestration",
    "path": "/docs/patterns/ai-agent-orchestration/concurrent-orchestration",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-agent-orchestration/group-chat-orchestration",
    "title": "Group Chat Orchestration",
    "path": "/docs/patterns/ai-agent-orchestration/group-chat-orchestration",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-agent-orchestration/handoff-orchestration",
    "title": "Handoff Orchestration",
    "path": "/docs/patterns/ai-agent-orchestration/handoff-orchestration",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-agent-orchestration/magentic-orchestration",
    "title": "Magentic Orchestration",
    "path": "/docs/patterns/ai-agent-orchestration/magentic-orchestration",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-agent-orchestration/sequential-orchestration",
    "title": "Sequential Orchestration",
    "path": "/docs/patterns/ai-agent-orchestration/sequential-orchestration",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-infra/feature-store",
    "title": "Feature Store",
    "path": "/docs/patterns/ai-infra/feature-store",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-infra/gpu-auto-scaling",
    "title": "GPU Auto-Scaling",
    "path": "/docs/patterns/ai-infra/gpu-auto-scaling",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-infra/llm-gateway",
    "title": "LLM Gateway",
    "path": "/docs/patterns/ai-infra/llm-gateway",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-infra/model-serving",
    "title": "Model Serving",
    "path": "/docs/patterns/ai-infra/model-serving",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-infra/rag-pipeline",
    "title": "RAG Pipeline",
    "path": "/docs/patterns/ai-infra/rag-pipeline",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-infra/semantic-caching",
    "title": "Semantic Caching",
    "path": "/docs/patterns/ai-infra/semantic-caching",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/ai-infra/vector-database-sharding",
    "title": "Vector Database Sharding",
    "path": "/docs/patterns/ai-infra/vector-database-sharding",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/busy-database",
    "title": "Busy Database",
    "path": "/docs/patterns/antipatterns/busy-database",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/busy-front-end",
    "title": "Busy Front End",
    "path": "/docs/patterns/antipatterns/busy-front-end",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/chatty-io",
    "title": "Chatty I/O",
    "path": "/docs/patterns/antipatterns/chatty-io",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/extraneous-fetching",
    "title": "Extraneous Fetching",
    "path": "/docs/patterns/antipatterns/extraneous-fetching",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/improper-instantiation",
    "title": "Improper Instantiation",
    "path": "/docs/patterns/antipatterns/improper-instantiation",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/monolithic-persistence",
    "title": "Monolithic Persistence",
    "path": "/docs/patterns/antipatterns/monolithic-persistence",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/no-caching",
    "title": "No Caching",
    "path": "/docs/patterns/antipatterns/no-caching",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/noisy-neighbor",
    "title": "Noisy Neighbor",
    "path": "/docs/patterns/antipatterns/noisy-neighbor",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/retry-storm",
    "title": "Retry Storm",
    "path": "/docs/patterns/antipatterns/retry-storm",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/antipatterns/synchronous-io",
    "title": "Synchronous I/O",
    "path": "/docs/patterns/antipatterns/synchronous-io",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/api-gateway",
    "title": "API Gateway",
    "path": "/docs/patterns/api-edge/api-gateway",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/api-versioning",
    "title": "API Versioning",
    "path": "/docs/patterns/api-edge/api-versioning",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/backend-for-frontend",
    "title": "Backend for Frontend",
    "path": "/docs/patterns/api-edge/backend-for-frontend",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/cursor-pagination",
    "title": "Cursor Pagination",
    "path": "/docs/patterns/api-edge/cursor-pagination",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/federated-identity",
    "title": "Federated Identity",
    "path": "/docs/patterns/api-edge/federated-identity",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/gateway-aggregation",
    "title": "Gateway Aggregation",
    "path": "/docs/patterns/api-edge/gateway-aggregation",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/gateway-offloading",
    "title": "Gateway Offloading",
    "path": "/docs/patterns/api-edge/gateway-offloading",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/gateway-routing",
    "title": "Gateway Routing",
    "path": "/docs/patterns/api-edge/gateway-routing",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/load-balancing",
    "title": "Load Balancing",
    "path": "/docs/patterns/api-edge/load-balancing",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/reverse-proxy",
    "title": "Reverse Proxy",
    "path": "/docs/patterns/api-edge/reverse-proxy",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/service-discovery",
    "title": "Service Discovery",
    "path": "/docs/patterns/api-edge/service-discovery",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/service-mesh",
    "title": "Service Mesh",
    "path": "/docs/patterns/api-edge/service-mesh",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/sidecar",
    "title": "Sidecar",
    "path": "/docs/patterns/api-edge/sidecar",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/api-edge/valet-key",
    "title": "Valet Key",
    "path": "/docs/patterns/api-edge/valet-key",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/backpressure",
    "title": "Backpressure",
    "path": "/docs/patterns/batch-streaming/backpressure",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/change-data-capture",
    "title": "Change Data Capture",
    "path": "/docs/patterns/batch-streaming/change-data-capture",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/competing-consumers",
    "title": "Competing Consumers",
    "path": "/docs/patterns/batch-streaming/competing-consumers",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/exactly-once-semantics",
    "title": "Exactly-Once Semantics",
    "path": "/docs/patterns/batch-streaming/exactly-once-semantics",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/lambda-kappa-architecture",
    "title": "Lambda & Kappa Architecture",
    "path": "/docs/patterns/batch-streaming/lambda-kappa-architecture",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/mapreduce",
    "title": "MapReduce",
    "path": "/docs/patterns/batch-streaming/mapreduce",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/partitioned-consumption",
    "title": "Partitioned Consumption",
    "path": "/docs/patterns/batch-streaming/partitioned-consumption",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/priority-queue",
    "title": "Priority Queue",
    "path": "/docs/patterns/batch-streaming/priority-queue",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/queue-based-load-leveling",
    "title": "Queue-Based Load Leveling",
    "path": "/docs/patterns/batch-streaming/queue-based-load-leveling",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/sequential-convoy",
    "title": "Sequential Convoy",
    "path": "/docs/patterns/batch-streaming/sequential-convoy",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/batch-streaming/stream-processing",
    "title": "Stream Processing",
    "path": "/docs/patterns/batch-streaming/stream-processing",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/blob-store",
    "title": "Blob Store",
    "path": "/docs/patterns/building-blocks/blob-store",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/cdn",
    "title": "CDN (Content Delivery Network)",
    "path": "/docs/patterns/building-blocks/cdn",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/distributed-cache",
    "title": "Distributed Cache",
    "path": "/docs/patterns/building-blocks/distributed-cache",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/distributed-logging",
    "title": "Distributed Logging",
    "path": "/docs/patterns/building-blocks/distributed-logging",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/distributed-message-queue",
    "title": "Distributed Message Queue",
    "path": "/docs/patterns/building-blocks/distributed-message-queue",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/distributed-monitoring",
    "title": "Distributed Monitoring",
    "path": "/docs/patterns/building-blocks/distributed-monitoring",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/distributed-search",
    "title": "Distributed Search",
    "path": "/docs/patterns/building-blocks/distributed-search",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/distributed-task-scheduler",
    "title": "Distributed Task Scheduler",
    "path": "/docs/patterns/building-blocks/distributed-task-scheduler",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/key-value-store",
    "title": "Key-Value Store",
    "path": "/docs/patterns/building-blocks/key-value-store",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/pipes-and-filters",
    "title": "Pipes and Filters",
    "path": "/docs/patterns/building-blocks/pipes-and-filters",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/rate-limiter",
    "title": "Rate Limiter",
    "path": "/docs/patterns/building-blocks/rate-limiter",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/scheduler-agent-supervisor",
    "title": "Scheduler Agent Supervisor",
    "path": "/docs/patterns/building-blocks/scheduler-agent-supervisor",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/sequencer",
    "title": "Sequencer",
    "path": "/docs/patterns/building-blocks/sequencer",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/sharded-counters",
    "title": "Sharded Counters",
    "path": "/docs/patterns/building-blocks/sharded-counters",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/static-content-hosting",
    "title": "Static Content Hosting",
    "path": "/docs/patterns/building-blocks/static-content-hosting",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/building-blocks/throttling",
    "title": "Throttling",
    "path": "/docs/patterns/building-blocks/throttling",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/caching/cache-aside",
    "title": "Cache-Aside",
    "path": "/docs/patterns/caching/cache-aside",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/caching/cache-stampede-prevention",
    "title": "Cache Stampede Prevention",
    "path": "/docs/patterns/caching/cache-stampede-prevention",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/caching/read-through",
    "title": "Read-Through",
    "path": "/docs/patterns/caching/read-through",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/caching/write-behind",
    "title": "Write-Behind",
    "path": "/docs/patterns/caching/write-behind",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/caching/write-through",
    "title": "Write-Through",
    "path": "/docs/patterns/caching/write-through",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/asynchronous-request-reply",
    "title": "Asynchronous Request-Reply",
    "path": "/docs/patterns/communication/asynchronous-request-reply",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/claim-check",
    "title": "Claim Check",
    "path": "/docs/patterns/communication/claim-check",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/event-driven-architecture",
    "title": "Event-Driven Architecture",
    "path": "/docs/patterns/communication/event-driven-architecture",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/grpc-bidirectional-streaming",
    "title": "gRPC Bidirectional Streaming",
    "path": "/docs/patterns/communication/grpc-bidirectional-streaming",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/messaging-bridge",
    "title": "Messaging Bridge",
    "path": "/docs/patterns/communication/messaging-bridge",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/pub-sub",
    "title": "Publish-Subscribe",
    "path": "/docs/patterns/communication/pub-sub",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/server-sent-events",
    "title": "Server-Sent Events",
    "path": "/docs/patterns/communication/server-sent-events",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/webhooks",
    "title": "Webhooks",
    "path": "/docs/patterns/communication/webhooks",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/communication/websockets",
    "title": "WebSockets",
    "path": "/docs/patterns/communication/websockets",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/choreography",
    "title": "Choreography",
    "path": "/docs/patterns/consistency/choreography",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/compensating-transaction",
    "title": "Compensating Transaction",
    "path": "/docs/patterns/consistency/compensating-transaction",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/leader-election",
    "title": "Leader Election",
    "path": "/docs/patterns/consistency/leader-election",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/paxos",
    "title": "Paxos",
    "path": "/docs/patterns/consistency/paxos",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/quorum",
    "title": "Quorum",
    "path": "/docs/patterns/consistency/quorum",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/raft",
    "title": "Raft",
    "path": "/docs/patterns/consistency/raft",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/saga",
    "title": "Saga",
    "path": "/docs/patterns/consistency/saga",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/two-phase-commit",
    "title": "Two-Phase Commit",
    "path": "/docs/patterns/consistency/two-phase-commit",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/consistency/vector-clocks",
    "title": "Vector Clocks",
    "path": "/docs/patterns/consistency/vector-clocks",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/integration/ambassador",
    "title": "Ambassador",
    "path": "/docs/patterns/integration/ambassador",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/integration/anti-corruption-layer",
    "title": "Anti-Corruption Layer",
    "path": "/docs/patterns/integration/anti-corruption-layer",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/integration/gatekeeper",
    "title": "Gatekeeper",
    "path": "/docs/patterns/integration/gatekeeper",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/integration/quarantine",
    "title": "Quarantine",
    "path": "/docs/patterns/integration/quarantine",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/integration/strangler-fig",
    "title": "Strangler Fig",
    "path": "/docs/patterns/integration/strangler-fig",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/blue-green-deployment",
    "title": "Blue-Green Deployment",
    "path": "/docs/patterns/observability/blue-green-deployment",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/canary-deployment",
    "title": "Canary Deployment",
    "path": "/docs/patterns/observability/canary-deployment",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/deployment-stamps",
    "title": "Deployment Stamps",
    "path": "/docs/patterns/observability/deployment-stamps",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/distributed-tracing",
    "title": "Distributed Tracing",
    "path": "/docs/patterns/observability/distributed-tracing",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/external-configuration-store",
    "title": "External Configuration Store",
    "path": "/docs/patterns/observability/external-configuration-store",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/feature-flags",
    "title": "Feature Flags",
    "path": "/docs/patterns/observability/feature-flags",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/geode",
    "title": "Geode",
    "path": "/docs/patterns/observability/geode",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/observability/health-check",
    "title": "Health Check",
    "path": "/docs/patterns/observability/health-check",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/bulkhead",
    "title": "Bulkhead",
    "path": "/docs/patterns/reliability/bulkhead",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/circuit-breaker",
    "title": "Circuit Breaker",
    "path": "/docs/patterns/reliability/circuit-breaker",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/dead-letter-queue",
    "title": "Dead Letter Queue",
    "path": "/docs/patterns/reliability/dead-letter-queue",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/failover",
    "title": "Failover",
    "path": "/docs/patterns/reliability/failover",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/graceful-degradation",
    "title": "Graceful Degradation",
    "path": "/docs/patterns/reliability/graceful-degradation",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/idempotency",
    "title": "Idempotency",
    "path": "/docs/patterns/reliability/idempotency",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/retry-with-backoff",
    "title": "Retry with Backoff",
    "path": "/docs/patterns/reliability/retry-with-backoff",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/reliability/timeout",
    "title": "Timeout",
    "path": "/docs/patterns/reliability/timeout",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/scaling/auto-scaling",
    "title": "Auto-Scaling",
    "path": "/docs/patterns/scaling/auto-scaling",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/scaling/compute-resource-consolidation",
    "title": "Compute Resource Consolidation",
    "path": "/docs/patterns/scaling/compute-resource-consolidation",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/scaling/connection-pooling",
    "title": "Connection Pooling",
    "path": "/docs/patterns/scaling/connection-pooling",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/scaling/horizontal-scaling",
    "title": "Horizontal Scaling",
    "path": "/docs/patterns/scaling/horizontal-scaling",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/scaling/vertical-scaling",
    "title": "Vertical Scaling",
    "path": "/docs/patterns/scaling/vertical-scaling",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/consistent-hashing",
    "title": "Consistent Hashing",
    "path": "/docs/patterns/storage/consistent-hashing",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/cqrs",
    "title": "CQRS",
    "path": "/docs/patterns/storage/cqrs",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/event-sourcing",
    "title": "Event Sourcing",
    "path": "/docs/patterns/storage/event-sourcing",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/federation",
    "title": "Federation",
    "path": "/docs/patterns/storage/federation",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/index-table",
    "title": "Index Table",
    "path": "/docs/patterns/storage/index-table",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/materialized-view",
    "title": "Materialized View",
    "path": "/docs/patterns/storage/materialized-view",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/primary-replica-replication",
    "title": "Primary-Replica Replication",
    "path": "/docs/patterns/storage/primary-replica-replication",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/sharding",
    "title": "Sharding",
    "path": "/docs/patterns/storage/sharding",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "patterns/storage/write-ahead-log",
    "title": "Write-Ahead Log",
    "path": "/docs/patterns/storage/write-ahead-log",
    "category": "design-patterns",
    "source": "supplementary"
  },
  {
    "id": "intro",
    "title": "Motivation",
    "path": "/docs/intro",
    "category": "concepts",
    "source": "primer"
  }
];
